name: Playwright Web3 tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g yarn && yarn

      - name: Install Playwright dependencies
        run: yarn playwright install-deps

      # For now, we only need Chromium.
      - name: Install browsers for Playwright
        run: yarn playwright install chromium

      - name: Install linux dependencies
        run: |
          sudo apt-get install --no-install-recommends -y \
          xvfb

      - name: Build cache
        run: xvfb-run npx synpress playwright/wallet-setup
        env:
          WALLET_SEED_PHRASE: ${{ secrets.WALLET_SEED_PHRASE }}
          WALLET_PASSWORD: ${{ secrets.WALLET_PASSWORD }}
      - name: Run Playwright tests
        run: xvfb-run npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
